# ========================================
# Copyright (c) 2026 Music420bot
# All Rights Reserved.
# Powered By   : @yoi_420
# Type         : Telegram Music Bot
# Channel      : https://t.me/BOT420_UPDATE
# Unauthorized copying, modification, or redistribution
# of this source code without permission is prohibited.
# ========================================
services:
  - type: worker
    name: Music420bot
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python -m Music420bot
    plan: free
    
